/*
 * JCudnn - Java bindings for cuDNN, the NVIDIA CUDA
 * Deep Neural Network library, to be used with JCuda
 *
 * Copyright (c) 2015-2015 Marco Hutter - http://www.jcuda.org
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jcuda_jcudnn_JCudnn */

#ifndef _Included_jcuda_jcudnn_JCudnn
#define _Included_jcuda_jcudnn_JCudnn
#ifdef __cplusplus
extern "C" {
#endif
#undef jcuda_jcudnn_JCudnn_CUDNN_MAJOR
#define jcuda_jcudnn_JCudnn_CUDNN_MAJOR 4L
#undef jcuda_jcudnn_JCudnn_CUDNN_MINOR
#define jcuda_jcudnn_JCudnn_CUDNN_MINOR 0L
#undef jcuda_jcudnn_JCudnn_CUDNN_PATCHLEVEL
#define jcuda_jcudnn_JCudnn_CUDNN_PATCHLEVEL 4L
#undef jcuda_jcudnn_JCudnn_CUDNN_VERSION
#define jcuda_jcudnn_JCudnn_CUDNN_VERSION 4004L
#undef jcuda_jcudnn_JCudnn_CUDNN_DIM_MAX
#define jcuda_jcudnn_JCudnn_CUDNN_DIM_MAX 8L
#undef jcuda_jcudnn_JCudnn_CUDNN_BN_MIN_EPSILON
#define jcuda_jcudnn_JCudnn_CUDNN_BN_MIN_EPSILON 1.0E-5
    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    setLogLevelNative
    * Signature: (I)V
    */
    JNIEXPORT void JNICALL Java_jcuda_jcudnn_JCudnn_setLogLevelNative
        (JNIEnv *, jclass, jint);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetVersionNative
    * Signature: ()J
    */
    JNIEXPORT jlong JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetVersionNative
        (JNIEnv *, jclass);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetErrorStringNative
    * Signature: (I)Ljava/lang/String;
    */
    JNIEXPORT jstring JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetErrorStringNative
        (JNIEnv *, jclass, jint);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnCreateNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnCreateNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnDestroyNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnDestroyNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetStreamNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetStreamNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetStreamNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/runtime/cudaStream_t;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetStreamNative
        (JNIEnv *, jclass, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnCreateTensorDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnTensorDescriptor;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnCreateTensorDescriptorNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetTensor4dDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnTensorDescriptor;IIIIII)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetTensor4dDescriptorNative
        (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jint);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetTensor4dDescriptorExNative
    * Signature: (Ljcuda/jcudnn/cudnnTensorDescriptor;IIIIIIIII)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetTensor4dDescriptorExNative
        (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetTensor4dDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnTensorDescriptor;[ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetTensor4dDescriptorNative
        (JNIEnv *, jclass, jobject, jintArray, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetTensorNdDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnTensorDescriptor;II[I[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetTensorNdDescriptorNative
        (JNIEnv *, jclass, jobject, jint, jint, jintArray, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetTensorNdDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnTensorDescriptor;I[I[I[I[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetTensorNdDescriptorNative
        (JNIEnv *, jclass, jobject, jint, jintArray, jintArray, jintArray, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnDestroyTensorDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnTensorDescriptor;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnDestroyTensorDescriptorNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnTransformTensorNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnTransformTensorNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnAddTensorNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnAddTensorNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnAddTensor_v3Native
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnAddTensor_1v3Native
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetTensorNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetTensorNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnScaleTensorNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnScaleTensorNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnCreateFilterDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnFilterDescriptor;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnCreateFilterDescriptorNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetFilter4dDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnFilterDescriptor;IIIII)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetFilter4dDescriptorNative
        (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetFilter4dDescriptor_v4Native
    * Signature: (Ljcuda/jcudnn/cudnnFilterDescriptor;IIIIII)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetFilter4dDescriptor_1v4Native
        (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jint);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetFilter4dDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnFilterDescriptor;[ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetFilter4dDescriptorNative
        (JNIEnv *, jclass, jobject, jintArray, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetFilter4dDescriptor_v4Native
    * Signature: (Ljcuda/jcudnn/cudnnFilterDescriptor;[I[ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetFilter4dDescriptor_1v4Native
        (JNIEnv *, jclass, jobject, jintArray, jintArray, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetFilterNdDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnFilterDescriptor;II[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetFilterNdDescriptorNative
        (JNIEnv *, jclass, jobject, jint, jint, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetFilterNdDescriptor_v4Native
    * Signature: (Ljcuda/jcudnn/cudnnFilterDescriptor;III[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetFilterNdDescriptor_1v4Native
        (JNIEnv *, jclass, jobject, jint, jint, jint, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetFilterNdDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnFilterDescriptor;I[ILjcuda/Pointer;[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetFilterNdDescriptorNative
        (JNIEnv *, jclass, jobject, jint, jintArray, jobject, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetFilterNdDescriptor_v4Native
    * Signature: (Ljcuda/jcudnn/cudnnFilterDescriptor;I[I[ILjcuda/Pointer;[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetFilterNdDescriptor_1v4Native
        (JNIEnv *, jclass, jobject, jint, jintArray, jintArray, jobject, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnDestroyFilterDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnFilterDescriptor;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnDestroyFilterDescriptorNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnCreateConvolutionDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnConvolutionDescriptor;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnCreateConvolutionDescriptorNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetConvolution2dDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnConvolutionDescriptor;IIIIIII)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetConvolution2dDescriptorNative
        (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jint, jint);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetConvolution2dDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnConvolutionDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetConvolution2dDescriptorNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetConvolution2dForwardOutputDimNative
    * Signature: (Ljcuda/jcudnn/cudnnConvolutionDescriptor;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/jcudnn/cudnnFilterDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetConvolution2dForwardOutputDimNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetConvolutionNdDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnConvolutionDescriptor;I[I[I[III)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetConvolutionNdDescriptorNative
        (JNIEnv *, jclass, jobject, jint, jintArray, jintArray, jintArray, jint, jint);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetConvolutionNdDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnConvolutionDescriptor;I[I[I[I[I[I[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetConvolutionNdDescriptorNative
        (JNIEnv *, jclass, jobject, jint, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetConvolutionNdDescriptor_v3Native
    * Signature: (Ljcuda/jcudnn/cudnnConvolutionDescriptor;I[I[I[III)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetConvolutionNdDescriptor_1v3Native
        (JNIEnv *, jclass, jobject, jint, jintArray, jintArray, jintArray, jint, jint);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetConvolutionNdDescriptor_v3Native
    * Signature: (Ljcuda/jcudnn/cudnnConvolutionDescriptor;I[I[I[I[I[I[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetConvolutionNdDescriptor_1v3Native
        (JNIEnv *, jclass, jobject, jint, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetConvolutionNdForwardOutputDimNative
    * Signature: (Ljcuda/jcudnn/cudnnConvolutionDescriptor;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/jcudnn/cudnnFilterDescriptor;I[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetConvolutionNdForwardOutputDimNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jint, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnDestroyConvolutionDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnConvolutionDescriptor;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnDestroyConvolutionDescriptorNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnFindConvolutionForwardAlgorithmNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/jcudnn/cudnnFilterDescriptor;Ljcuda/jcudnn/cudnnConvolutionDescriptor;Ljcuda/jcudnn/cudnnTensorDescriptor;I[I[Ljcuda/jcudnn/cudnnConvolutionFwdAlgoPerf;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnFindConvolutionForwardAlgorithmNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jint, jintArray, jobjectArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetConvolutionForwardAlgorithmNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/jcudnn/cudnnFilterDescriptor;Ljcuda/jcudnn/cudnnConvolutionDescriptor;Ljcuda/jcudnn/cudnnTensorDescriptor;IJ[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetConvolutionForwardAlgorithmNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jint, jlong, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetConvolutionForwardWorkspaceSizeNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/jcudnn/cudnnFilterDescriptor;Ljcuda/jcudnn/cudnnConvolutionDescriptor;Ljcuda/jcudnn/cudnnTensorDescriptor;I[J)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetConvolutionForwardWorkspaceSizeNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jint, jlongArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnConvolutionForwardNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnFilterDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnConvolutionDescriptor;ILjcuda/Pointer;JLjcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnConvolutionForwardNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jint, jobject, jlong, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnConvolutionBackwardBiasNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnConvolutionBackwardBiasNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnFindConvolutionBackwardFilterAlgorithmNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/jcudnn/cudnnConvolutionDescriptor;Ljcuda/jcudnn/cudnnFilterDescriptor;I[I[Ljcuda/jcudnn/cudnnConvolutionBwdFilterAlgoPerf;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnFindConvolutionBackwardFilterAlgorithmNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jint, jintArray, jobjectArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetConvolutionBackwardFilterAlgorithmNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/jcudnn/cudnnConvolutionDescriptor;Ljcuda/jcudnn/cudnnFilterDescriptor;IJ[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetConvolutionBackwardFilterAlgorithmNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jint, jlong, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetConvolutionBackwardFilterWorkspaceSizeNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/jcudnn/cudnnConvolutionDescriptor;Ljcuda/jcudnn/cudnnFilterDescriptor;I[J)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetConvolutionBackwardFilterWorkspaceSizeNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jint, jlongArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnConvolutionBackwardFilterNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnConvolutionDescriptor;ILjcuda/Pointer;JLjcuda/Pointer;Ljcuda/jcudnn/cudnnFilterDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnConvolutionBackwardFilterNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jint, jobject, jlong, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnConvolutionBackwardFilter_v3Native
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnConvolutionDescriptor;ILjcuda/Pointer;JLjcuda/Pointer;Ljcuda/jcudnn/cudnnFilterDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnConvolutionBackwardFilter_1v3Native
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jint, jobject, jlong, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnFindConvolutionBackwardDataAlgorithmNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnFilterDescriptor;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/jcudnn/cudnnConvolutionDescriptor;Ljcuda/jcudnn/cudnnTensorDescriptor;I[I[Ljcuda/jcudnn/cudnnConvolutionBwdDataAlgoPerf;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnFindConvolutionBackwardDataAlgorithmNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jint, jintArray, jobjectArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetConvolutionBackwardDataAlgorithmNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnFilterDescriptor;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/jcudnn/cudnnConvolutionDescriptor;Ljcuda/jcudnn/cudnnTensorDescriptor;IJ[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetConvolutionBackwardDataAlgorithmNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jint, jlong, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetConvolutionBackwardDataWorkspaceSizeNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnFilterDescriptor;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/jcudnn/cudnnConvolutionDescriptor;Ljcuda/jcudnn/cudnnTensorDescriptor;I[J)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetConvolutionBackwardDataWorkspaceSizeNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jint, jlongArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnConvolutionBackwardDataNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnFilterDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnConvolutionDescriptor;ILjcuda/Pointer;JLjcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnConvolutionBackwardDataNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jint, jobject, jlong, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnConvolutionBackwardData_v3Native
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnFilterDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnConvolutionDescriptor;ILjcuda/Pointer;JLjcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnConvolutionBackwardData_1v3Native
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jint, jobject, jlong, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnIm2ColNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnFilterDescriptor;Ljcuda/jcudnn/cudnnConvolutionDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnIm2ColNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSoftmaxForwardNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;IILjcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSoftmaxForwardNative
        (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSoftmaxBackwardNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;IILjcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSoftmaxBackwardNative
        (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnCreatePoolingDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnPoolingDescriptor;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnCreatePoolingDescriptorNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetPooling2dDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnPoolingDescriptor;IIIIIII)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetPooling2dDescriptorNative
        (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jint, jint);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetPooling2dDescriptor_v4Native
    * Signature: (Ljcuda/jcudnn/cudnnPoolingDescriptor;IIIIIIII)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetPooling2dDescriptor_1v4Native
        (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetPooling2dDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnPoolingDescriptor;[ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetPooling2dDescriptorNative
        (JNIEnv *, jclass, jobject, jintArray, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetPooling2dDescriptor_v4Native
    * Signature: (Ljcuda/jcudnn/cudnnPoolingDescriptor;[I[ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetPooling2dDescriptor_1v4Native
        (JNIEnv *, jclass, jobject, jintArray, jintArray, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetPoolingNdDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnPoolingDescriptor;II[I[I[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetPoolingNdDescriptorNative
        (JNIEnv *, jclass, jobject, jint, jint, jintArray, jintArray, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetPoolingNdDescriptor_v4Native
    * Signature: (Ljcuda/jcudnn/cudnnPoolingDescriptor;III[I[I[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetPoolingNdDescriptor_1v4Native
        (JNIEnv *, jclass, jobject, jint, jint, jint, jintArray, jintArray, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetPoolingNdDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnPoolingDescriptor;I[ILjcuda/Pointer;[I[I[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetPoolingNdDescriptorNative
        (JNIEnv *, jclass, jobject, jint, jintArray, jobject, jintArray, jintArray, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetPoolingNdDescriptor_v4Native
    * Signature: (Ljcuda/jcudnn/cudnnPoolingDescriptor;I[I[ILjcuda/Pointer;[I[I[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetPoolingNdDescriptor_1v4Native
        (JNIEnv *, jclass, jobject, jint, jintArray, jintArray, jobject, jintArray, jintArray, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetPoolingNdForwardOutputDimNative
    * Signature: (Ljcuda/jcudnn/cudnnPoolingDescriptor;Ljcuda/jcudnn/cudnnTensorDescriptor;I[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetPoolingNdForwardOutputDimNative
        (JNIEnv *, jclass, jobject, jobject, jint, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetPooling2dForwardOutputDimNative
    * Signature: (Ljcuda/jcudnn/cudnnPoolingDescriptor;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetPooling2dForwardOutputDimNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnDestroyPoolingDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnPoolingDescriptor;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnDestroyPoolingDescriptorNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnPoolingForwardNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnPoolingDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnPoolingForwardNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnPoolingBackwardNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnPoolingDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnPoolingBackwardNative
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnCreateActivationDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnActivationDescriptor;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnCreateActivationDescriptorNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetActivationDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnActivationDescriptor;IID)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetActivationDescriptorNative
        (JNIEnv *, jclass, jobject, jint, jint, jdouble);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetActivationDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnActivationDescriptor;[I[ILjcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetActivationDescriptorNative
        (JNIEnv *, jclass, jobject, jintArray, jintArray, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnDestroyActivationDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnActivationDescriptor;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnDestroyActivationDescriptorNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnActivationForwardNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;ILjcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnActivationForwardNative
        (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnActivationForward_v4Native
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnActivationDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnActivationForward_1v4Native
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnActivationBackwardNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;ILjcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnActivationBackwardNative
        (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnActivationBackward_v4Native
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnActivationDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnActivationBackward_1v4Native
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnCreateLRNDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnLRNDescriptor;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnCreateLRNDescriptorNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetLRNDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnLRNDescriptor;IDDD)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetLRNDescriptorNative
        (JNIEnv *, jclass, jobject, jint, jdouble, jdouble, jdouble);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetLRNDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnLRNDescriptor;[ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetLRNDescriptorNative
        (JNIEnv *, jclass, jobject, jintArray, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnDestroyLRNDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnLRNDescriptor;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnDestroyLRNDescriptorNative
        (JNIEnv *, jclass, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnLRNCrossChannelForwardNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnLRNDescriptor;ILjcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnLRNCrossChannelForwardNative
        (JNIEnv *, jclass, jobject, jobject, jint, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnLRNCrossChannelBackwardNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnLRNDescriptor;ILjcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnLRNCrossChannelBackwardNative
        (JNIEnv *, jclass, jobject, jobject, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnDivisiveNormalizationForwardNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnLRNDescriptor;ILjcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnDivisiveNormalizationForwardNative
        (JNIEnv *, jclass, jobject, jobject, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnDivisiveNormalizationBackwardNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/jcudnn/cudnnLRNDescriptor;ILjcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnDivisiveNormalizationBackwardNative
        (JNIEnv *, jclass, jobject, jobject, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnDeriveBNTensorDescriptorNative
    * Signature: (Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/jcudnn/cudnnTensorDescriptor;I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnDeriveBNTensorDescriptorNative
        (JNIEnv *, jclass, jobject, jobject, jint);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnBatchNormalizationForwardTrainingNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;DLjcuda/Pointer;Ljcuda/Pointer;DLjcuda/Pointer;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnBatchNormalizationForwardTrainingNative
        (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jdouble, jobject, jobject, jdouble, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnBatchNormalizationForwardInferenceNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;D)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnBatchNormalizationForwardInferenceNative
        (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jdouble);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnBatchNormalizationBackwardNative
    * Signature: (Ljcuda/jcudnn/cudnnHandle;ILjcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/Pointer;DLjcuda/Pointer;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnBatchNormalizationBackwardNative
        (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jdouble, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnSetConvolutionNdDescriptor_v2Native
    * Signature: (Ljcuda/jcudnn/cudnnConvolutionDescriptor;I[I[I[II)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnSetConvolutionNdDescriptor_1v2Native
        (JNIEnv *, jclass, jobject, jint, jintArray, jintArray, jintArray, jint);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnGetConvolutionNdDescriptor_v2Native
    * Signature: (Ljcuda/jcudnn/cudnnConvolutionDescriptor;I[I[I[I[I[I)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnGetConvolutionNdDescriptor_1v2Native
        (JNIEnv *, jclass, jobject, jint, jintArray, jintArray, jintArray, jintArray, jintArray);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnAddTensor_v2Native
    * Signature: (Ljcuda/jcudnn/cudnnHandle;ILjcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnAddTensor_1v2Native
        (JNIEnv *, jclass, jobject, jint, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnConvolutionBackwardFilter_v2Native
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnConvolutionDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnFilterDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnConvolutionBackwardFilter_1v2Native
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

    /*
    * Class:     jcuda_jcudnn_JCudnn
    * Method:    cudnnConvolutionBackwardData_v2Native
    * Signature: (Ljcuda/jcudnn/cudnnHandle;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnFilterDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnConvolutionDescriptor;Ljcuda/Pointer;Ljcuda/jcudnn/cudnnTensorDescriptor;Ljcuda/Pointer;)I
    */
    JNIEXPORT jint JNICALL Java_jcuda_jcudnn_JCudnn_cudnnConvolutionBackwardData_1v2Native
        (JNIEnv *, jclass, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
